directories:
  output: ${productName}-${version}
  buildResources: build
appId: co.duty-free.app
asar: true
artifactName: ${productName}-${version}.${ext}
productName: duty_free
dmg:
  contents:
    - x: 110
      'y': 150
    - x: 240
      'y': 150
      type: link
      path: /Applications
linux:
  target:
    - AppImage
    - deb
win:
  target: nsis
  icon: build/duty.jpg
  publisherName: ciberi.co
  publish:
    - provider: s3
      bucket: app-duty-free
      region: us-east-2
      channel: latest
nsis:
  oneClick: false
  installerIcon: icon.ico
  uninstallerIcon: icon.ico
  uninstallDisplayName: Desistalar ciberi duty-free
  license: licence.md
  allowToChangeInstallationDirectory: true
extraFiles:
  - from: ./public
    to: public
  - from: ./logs
    to: logs
files:
  - filter:
      - '**/*'
electronVersion: 17.1.0
